### ISSUE TITLE
Error reported when saving the model after training finished

### ISSUE THREAD

**Issue by guanghuili98** [LetterLiGo/SafeEar#16]
python train.py --conf_dir config/train19.yaml
After Training Finished, the error message is as follows:, AttributeError: 'SafeEar1s' object has no attribute 'serialize'
Traceback (most recent call last):
  File "/home/liguanghui/audio_deepfake/SafeEar/train.py", line 214, in <module>
    train(cfg)
  File "/home/liguanghui/audio_deepfake/SafeEar/train.py", line 191, in train
    to_save = system.detect_model.serialize()
  File "/home/liguanghui/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SafeEar1s' object has no attribute 'serialize'

**Comment by taimoorkhokhar** [comment]
Faced similar issue what did you do for a workaround? I simply removed the serialize line and saved it without serialize()
