### ISSUE TITLE
关于requirement的问题以及test.py的问题

### ISSUE THREAD

**Issue by HelloRuccs** [LetterLiGo/SafeEar#8]
开发者你好，关于test.py Exp是ASVspoof19我在执行的过程中遇到了如下问题
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "test.py", line 77, in <module>
[rank0]:     train(cfg, args)
[rank0]:   File "test.py", line 55, in train
[rank0]:     trainer.test(system, datamodule=datamodule, ckpt_path=args.ckpt_path)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 748, in test
[rank0]:     return call._call_and_handle_interrupt(
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 788, in _test_impl
[rank0]:     results = self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1018, in _run_stage
[rank0]:     return self._evaluation_loop.run()
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
[rank0]:     return loop_run(self, *args, **kwargs)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 128, in run
[rank0]:     batch, batch_idx, dataloader_idx = next(data_fetcher)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
[rank0]:     batch = super().__next__()
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
[rank0]:     out = next(self.iterators[0])
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
[rank0]:     raise exception
[rank0]: RuntimeError: Caught RuntimeError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
[rank0]:     return self.collate_fn(data)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 317, in default_collate
[rank0]:     return collate(batch, collate_fn_map=default_collate_fn_map)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 174, in collate
[rank0]:     return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 174, in <listcomp>
[rank0]:     return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
[rank0]:     return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
[rank0]:   File "/home/chenjiawei123/.conda/envs/safeear/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 214, in collate_tensor_fn
[rank0]:     return torch.stack(batch, 0, out=out)
[rank0]: RuntimeError: stack expects each tensor to be equal size, but got [1, 22831] at entry 0 and [1, 63623] at entry 1
```
主要是tensor长度不一的原因 我的训练是可以正常进行的，我怀疑是pytorch_lightning版本的问题 我pip  requirement.txt的时候无法下载1.6.3最后下了2.4.0 我尝试了很久无法完全准确按照requirement安装每一个版本包 我需要要一份safeear的conda环境压缩包

**Comment by LetterLiGo** [comment]
Find the env.yml
```
name: Lxf-safeear
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.11.17=hbcca054_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.7.0=h439df22_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.2.1=py38h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pysoundfile=0.11.0=pyhd8ed1ab_0
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - audioread==3.0.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bitarray==2.8.2
    - black==19.10b0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.16.0
    - cfgv==3.4.0
    - charset-normalizer==3.3.0
    - click==8.1.7
    - cmake==3.27.5
    - colorama==0.4.6
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==3.0.3
    - decorator==5.1.1
    - distlib==0.3.8
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - entrypoints==0.3
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fairseq==1.0.0a0+4acaa61
    - ffmpeg==1.4
    - ffmpegio==0.8.6
    - ffmpegio-core==0.8.6
    - filelock==3.12.4
    - flake8==3.7.9
    - fonttools==4.43.1
    - frozenlist==1.4.0
    - fsspec==2023.9.2
    - fvcore==0.1.5.post20221221
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.40
    - google-auth==2.23.2
    - google-auth-oauthlib==1.0.0
    - grpcio==1.59.0
    - h5py==3.9.0
    - huggingface-hub==0.20.1
    - hydra-core==1.1.2
    - hyperpyyaml==1.2.2
    - identify==2.5.33
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==5.2.3
    - iniconfig==2.0.0
    - iopath==0.1.10
    - ipdb==0.13.13
    - ipython==8.12.3
    - jedi==0.19.1
    - jinja2==3.1.2
    - jiwer==3.0.4
    - joblib==1.3.2
    - julius==0.2.7
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - librosa==0.10.1
    - lightning-utilities==0.9.0
    - lit==17.0.1
    - llvmlite==0.41.0
    - lxml==4.9.3
    - markdown==3.4.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.7.3
    - matplotlib-inline==0.1.6
    - mccabe==0.6.1
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - networkx==3.1
    - nodeenv==1.8.0
    - npy-append-array==0.9.16
    - numba==0.58.0
    - numpy==1.22.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-ml-py==12.535.133
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - nvitop==1.3.1
    - oauthlib==3.2.2
    - omegaconf==2.1.2
    - packaging==23.2
    - pandas==2.0.3
    - parso==0.8.3
    - pathspec==0.12.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.0.1
    - platformdirs==3.10.0
    - pluggy==1.3.0
    - pooch==1.7.0
    - portalocker==2.8.2
    - pre-commit==3.5.0
    - prompt-toolkit==3.0.40
    - protobuf==4.24.3
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.16.1
    - pyparsing==3.1.1
    - pysocks==1.7.1
    - pytest==7.4.0
    - python-dateutil==2.8.2
    - pytorch-lightning==2.1.0
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - rapidfuzz==3.9.0
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.6.0
    - rsa==4.9
    - ruamel-yaml==0.18.5
    - ruamel-yaml-clib==0.2.8
    - sacrebleu==2.3.1
    - safetensors==0.3.3
    - scikit-learn==1.3.1
    - scipy==1.10.1
    - sentencepiece==0.1.99
    - sentry-sdk==1.32.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - soundfile==0.12.1
    - soupsieve==2.5
    - sox==1.4.1
    - soxr==0.3.6
    - speechbrain==0.5.14
    - speechtokenizer==0.1.2
    - stack-data==0.6.3
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.2.0
    - timm==0.9.7
    - tokenizers==0.15.0
    - toml==0.10.2
    - tomli==2.0.1
    - torch==2.1.0+cu118
    - torch-kmeans==0.2.0
    - torchaudio==2.1.0+cu118
    - torchmetrics==1.2.0
    - torchvision==0.16.0+cu118
    - tqdm==4.66.1
    - traitlets==5.13.0
    - transformers==4.36.2
    - triton==2.1.0
    - typed-ast==1.5.5
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - urllib3==2.0.5
    - virtualenv==20.25.0
    - wandb==0.15.12
    - wcwidth==0.2.9
    - werkzeug==3.0.0
    - yacs==0.1.8
    - yamllint==1.23.0
    - yarl==1.9.2
    - zipp==3.17.0
prefix: /opt/anaconda3/envs/Lxf-safeear
```

**Comment by jun-mei** [comment]
想问一下是怎么解决这个问题的，我运行test时也遇到了这个问题，pytorch-lightning版本和作者是一致的

**Comment by HelloRuccs** [comment]
还没解决诶 更换omegaconf版本也不行

**Comment by HelloRuccs** [comment]
> 想问一下是怎么解决这个问题的，我运行test时也遇到了这个问题，pytorch-lightning版本和作者是一致的
请问你后续跑通了吗

**Comment by jun-mei** [comment]
还没有跑通

> > 想问一下是怎么解决这个问题的，我运行test时也遇到了这个问题，pytorch-lightning版本和作者是一致的
> > 请问你后续跑通了吗

**Comment by HelloRuccs** [comment]
> 还没有跑通
> 
> > > 想问一下是怎么解决这个问题的，我运行test时也遇到了这个问题，pytorch-lightning版本和作者是一致的
> > > 请问你后续跑通了吗

老哥 你的fairseq 还有omegaconf版本是多少 之前开发者让我换omegaconf==2.1.2  我没换成功

**Comment by jun-mei** [comment]
>omegaconf版本和hydra-core版本挂钩的好像，你下载hydra-core==1.1.2这个omegaconf就自动下载成2.1.2了，我的fairseq是                0.12.2

**Comment by HelloRuccs** [comment]
> > omegaconf版本和hydra-core版本挂钩的好像，你下载hydra-core==1.1.2这个omegaconf就自动下载成2.1.2了，我的fairseq是                0.12.2

好像这几个版本会冲突

**Comment by jun-mei** [comment]
我是用pip install hydra-core==1.1.2直接下下来的，我的版本没有冲突

**Comment by HelloRuccs** [comment]
> 我是用pip install hydra-core==1.1.2直接下下来的，我的版本没有冲突

我现在还是不行 ，还是
![image](https://github.com/user-attachments/assets/8b1f7dbb-dc57-4c98-aec4-cd7919974a12)
方便交流一下吗

**Comment by HollowYUK** [comment]
> > 我是用pip install hydra-core==1.1.2直接下下来的，我的版本没有冲突
> 
> 我现在还是不行 ，还是 ![image](https://private-user-images.githubusercontent.com/100855761/383067498-8b1f7dbb-dc57-4c98-aec4-cd7919974a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjY1NTMsIm5iZiI6MTczNTI2NjI1MywicGF0aCI6Ii8xMDA4NTU3NjEvMzgzMDY3NDk4LThiMWY3ZGJiLWRjNTctNGM5OC1hZWM0LWNkNzkxOTk3NGExMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMjI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODJiNTJjYTA0OTVmM2M3YTNmZTE0YTFhYTEwNDE0ZTRiNWRkNDJjZDgwOTg1Yzc4ZWNkYmExNTdkYmE5MGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SIyu0N9pI0B7bzW5zsaRb9BZwODYNRXBqr2GDdFbasE) 方便交流一下吗

打扰了，请问你最后有没有解决这个问题，我复现时也出现了同样的问题

**Comment by sunskybrave** [comment]
打扰了，想问下大家都是用的linux环境吗？有使用windows环境的吗？ 我安装triton-2.0.0发现这个依赖不支持windows

**Comment by JusperLee** [comment]
batch=1就可以了。

**Comment by luhaitaotao** [comment]
@JusperLee 您好 是将配置文件或者asvspoof19.py里的batch_size改为1吗？我尝试着这样做了，代码产生了如下的错误

  File "/home/user/anaconda3/envs/safeear/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/user/anaconda3/envs/safeear/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/user/anaconda3/envs/safeear/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 220, in _evaluation_step
    output = self.trainer._call_strategy_hook("test_step", *kwargs.values())
  File "/home/user/anaconda3/envs/safeear/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/safeear/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 354, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/home/user/Documents/luhaitao/safeear-main01/safeear/trainer/safeear_trainer.py", line 121, in test_step
    audio_path, raw_former_loss_, raw_logits, target = self(batch, is_train=False)
ValueError: not enough values to unpack (expected 4, got 3)
Testing DataLoader 0:   0%|          | 0/71237 [00:01<?, ?it/s]

**Comment by luhaitaotao** [comment]
@JusperLee 开发者您好，我是一名深度学习的初学者，首先万分感谢您回答了我之前的问题，我根据您最新的代码复现了实验，目前仅仅使用了ASVspoof2019的数据集，我在您的论文中看到了有关t-DCF的指标，我想知道如何查看这个指标数据

![Image](https://github.com/user-attachments/assets/c399a249-3fa2-4ede-9352-da0d3d61f5bd)
